//! Minimal, read-only SOV block-header wire contract used to authenticate work.

use borsh::{BorshDeserialize, BorshSerialize};

#[derive(Clone, Debug, PartialEq, Eq, BorshSerialize, BorshDeserialize)]
pub(crate) struct BlockHeaderWire {
    pub(crate) height: u64,
    pub(crate) _prev_hash: [u8; 32],
    pub(crate) _tx_root: [u8; 32],
    pub(crate) _receipts_root: [u8; 32],
    pub(crate) _state_root: [u8; 32],
    pub(crate) timestamp_ms: u64,
    pub(crate) proposer: String,
    pub(crate) version_bits: u32,
    pub(crate) bits: u32,
    pub(crate) _nonce: u64,
}

pub(crate) fn template_id_for_blob(blob: &[u8]) -> String {
    hex::encode(blake3::hash(blob).as_bytes())
}

pub(crate) fn validate_account_id(account: &str) -> Result<(), String> {
    let bytes = account.as_bytes();
    if !(2..=64).contains(&bytes.len()) {
        return Err(format!(
            "account length {} is outside 2..=64 bytes",
            bytes.len()
        ));
    }
    let separator = |byte: u8| matches!(byte, b'-' | b'_' | b'.');
    if separator(bytes[0]) || separator(bytes[bytes.len() - 1]) {
        return Err("account cannot start or end with a separator".into());
    }
    let mut previous_was_separator = false;
    for &byte in bytes {
        if !(byte.is_ascii_lowercase() || byte.is_ascii_digit() || separator(byte)) {
            return Err("account contains a character outside a-z, 0-9, -, _, .".into());
        }
        if separator(byte) && previous_was_separator {
            return Err("account contains adjacent separators".into());
        }
        previous_was_separator = separator(byte);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    // Captured from a real `sov_getBlockTemplate` response at height 10232.
    // This is a fixed compatibility vector, not generated by this wire struct.
    const SOV_HEADER_BLOB: &str = "f827000000000000f0f5d16f1ab1156090c67ecae16e2bf2000ad42f5d33a30660a9f928c12a97582d3adedff11b61f14c886e35afa036736dcd87a74d27b5c1510225d0f592e2132d3adedff11b61f14c886e35afa036736dcd87a74d27b5c1510225d0f592e2135316dc16a06107672c9d20613045329bb38720150901bd1b1b9fa2fd61ff06170b2ecf8b9f010000400000006133353735356433386136323664653162323538323039313361616462653832393962366666366138643033333864646566353239356337343434633165323400000000b1ad3e1e0000000000000000";

    #[test]
    fn live_sov_header_vector_decodes_and_identifies_exactly() {
        let blob = hex::decode(SOV_HEADER_BLOB).unwrap();
        let header = BlockHeaderWire::try_from_slice(&blob).unwrap();
        assert_eq!(header.height, 10_232);
        assert_eq!(header.timestamp_ms, 1_784_757_038_603);
        assert_eq!(
            header.proposer,
            "a35755d38a626de1b25820913aadbe8299b6ff6a8d0338ddef5295c7444c1e24"
        );
        assert_eq!(header.version_bits, 0);
        assert_eq!(header.bits, 507_424_177);
        assert_eq!(
            template_id_for_blob(&blob),
            "8a1b5154138c14d8bdc6062663809b689d6c3925d53ed634a5c805eea982ace7"
        );
    }

    #[test]
    fn account_validation_matches_the_sov_wire_rules() {
        assert!(validate_account_id(
            "a35755d38a626de1b25820913aadbe8299b6ff6a8d0338ddef5295c7444c1e24"
        )
        .is_ok());
        assert!(validate_account_id("coinbase.sov").is_ok());
        assert!(validate_account_id("BAD").is_err());
        assert!(validate_account_id("bad..name").is_err());
        assert!(validate_account_id(".bad").is_err());
    }
}
